services:
  - type: web
    name: stock-management-backend
    env: docker
    plan: free
    buildCommand: docker build -t stock-management-backend .
    startCommand: docker run -p $PORT:80 stock-management-backend
    envVars:
      - key: APP_NAME
        value: "Gestion de Stock"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: stock-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: stock-management-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: stock-management-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: stock-management-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: stock-management-db
          property: password
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

databases:
  - name: stock-management-db
    plan: free
    databaseName: stock_management
    user: stock_management_user
